version: '2'
services:
    jhora-app:
        image: jhora
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jhora-oracle:1521:jhora
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
